"""change address

Revision ID: 9e689077a5e2
Revises: 2b3f8a613bd4
Create Date: 2018-04-25 17:30:21.947792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e689077a5e2'
down_revision = '2b3f8a613bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplier_address', table_name='supplier')
    op.create_index(op.f('ix_supplier_address'), 'supplier', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_address'), table_name='supplier')
    op.create_index('ix_supplier_address', 'supplier', ['address'], unique=1)
    # ### end Alembic commands ###
