"""coluna unity para o order_item

Revision ID: abff300c681d
Revises: d6e15de26d1b
Create Date: 2018-05-03 09:47:30.761718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abff300c681d'
down_revision = 'd6e15de26d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('unity', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'unity')
    # ### end Alembic commands ###
