"""coluna obs na tabela order

Revision ID: ee23bc477f3a
Revises: abff300c681d
Create Date: 2018-05-03 11:24:13.301706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee23bc477f3a'
down_revision = 'abff300c681d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('obs', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'obs')
    # ### end Alembic commands ###
