"""add supplier status

Revision ID: ee371494c246
Revises: 9e689077a5e2
Create Date: 2018-04-25 17:52:14.520012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee371494c246'
down_revision = '9e689077a5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('status', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_supplier_status'), 'supplier', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_status'), table_name='supplier')
    op.drop_column('supplier', 'status')
    # ### end Alembic commands ###
